name: Emscripten

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [Debug, Release]

    env:
      BUILD_TYPE: ${{matrix.type}}

    steps:
    - uses: actions/checkout@v4
    - uses: mymindstorm/setup-emsdk@v14

    - name: Test Emscripten
      run: emcc -v

    - name: Configure CMake
      run: emcmake cmake -B ${{github.workspace}}/out/web/${{env.BUILD_TYPE}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/out/web/${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}}
